import turtle
turtle.pensize(5)
turtle.speed(1)
turtle.color('red')
turtle.begin_fill()
turtle.fillcolor('red')
turtle.left(150)
turtle.forward(180)
turtle.circle(-90,180)
turtle.setheading(60)
turtle.circle(-90,180)
turtle.forward(180)
turtle.end_fill()
turtle.mainloop()
